[phases.setup]
aptPkgs = ["hugo"]

[phases.install]
cmds = ["hugo mod get github.com/imfing/hextra", "go mod tidy"]

[ phases.build ]
cmds = ["hugo mod get github.com/imfing/hextra", "hugo --gc --minify"]

[ environment ]
HUGO_VERSION = "0.132.2"

[[ nixpacks.included_files ]]
paths = ["/public"]