[phases.setup]
aptPkgs = ["hugo"]

[phases.install]
cmds = ["go mod tidy", "hugo mod get github.com/imfing/hextra"]

[ phases.build ]
cmds = ["hugo --gc --minify"]

[ environment ]
HUGO_VERSION = "0.132.2"

[[ nixpacks.included_files ]]
paths = ["/public"]